Excluded:
  - lib
  - "**/*.ecr"

Layout/LineLength:
  Enabled: true
  MaxLength: 120

Lint/NotNil:
  Enabled: false

Lint/NotNilAfterNoBang:
  Enabled: false

Lint/SpecFilename:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Naming/BlockParameterName:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RedundantSelf:
  Enabled: false
