Excluded:
  - "**/*.ecr"
  - example_projects
  - lib
  - "tmp"

Layout/LineLength:
  Enabled: true
  MaxLength: 120

Lint/NotNil:
  Enabled: false

Lint/SpecFilename:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Naming/BlockParameterName:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false
