module Marten
  module CLI
    abstract class Generator
      class Auth < App
        module Templates
          def self.app_files(context : Context)
            path_prefix = App::Templates.path_prefix(context)

            [
              {"#{path_prefix}app.cr", ECR.render("#{__DIR__}/../app/templates/app.cr.ecr")},
              {"#{path_prefix}cli.cr", ECR.render("#{__DIR__}/../app/templates/cli.cr.ecr")},
              {"#{path_prefix}routes.cr", ECR.render("#{__DIR__}/templates/app/routes.cr.ecr")},
              {
                "#{path_prefix}emails/password_reset_email.cr",
                ECR.render("#{__DIR__}/templates/app/emails/password_reset_email.cr.ecr"),
              },
              {
                "#{path_prefix}handlers/concerns/require_anonymous_user.cr",
                ECR.render(
                  "#{__DIR__}/templates/app/handlers/concerns/require_anonymous_user.cr.ecr",
                ),
              },
              {
                "#{path_prefix}handlers/concerns/require_signed_in_user.cr",
                ECR.render(
                  "#{__DIR__}/templates/app/handlers/concerns/require_signed_in_user.cr.ecr"
                ),
              },
              {
                "#{path_prefix}handlers/password_reset_confirm_handler.cr",
                ECR.render(
                  "#{__DIR__}/templates/app/handlers/password_reset_confirm_handler.cr.ecr"
                ),
              },
              {
                "#{path_prefix}handlers/password_reset_initiate_handler.cr",
                ECR.render(
                  "#{__DIR__}/templates/app/handlers/password_reset_initiate_handler.cr.ecr"
                ),
              },
              {
                "#{path_prefix}handlers/password_update_handler.cr",
                ECR.render(
                  "#{__DIR__}/templates/app/handlers/password_update_handler.cr.ecr"
                ),
              },
              {
                "#{path_prefix}handlers/profile_handler.cr",
                ECR.render("#{__DIR__}/templates/app/handlers/profile_handler.cr.ecr"),
              },
              {
                "#{path_prefix}handlers/sign_in_handler.cr",
                ECR.render("#{__DIR__}/templates/app/handlers/sign_in_handler.cr.ecr"),
              },
              {
                "#{path_prefix}handlers/sign_out_handler.cr",
                ECR.render("#{__DIR__}/templates/app/handlers/sign_out_handler.cr.ecr"),
              },
              {
                "#{path_prefix}handlers/sign_up_handler.cr",
                ECR.render("#{__DIR__}/templates/app/handlers/sign_up_handler.cr.ecr"),
              },
              {
                "#{path_prefix}migrations/0001_create_#{context.label}_user_table.cr",
                ECR.render(
                  "#{__DIR__}/templates/app/migrations/0001_create_auth_user_table.cr.ecr"
                ),
              },
              {
                "#{path_prefix}models/user.cr",
                ECR.render("#{__DIR__}/templates/app/models/user.cr.ecr"),
              },
              {
                "#{path_prefix}schemas/password_reset_confirm_schema.cr",
                ECR.render("#{__DIR__}/templates/app/schemas/password_reset_confirm_schema.cr.ecr"),
              },
              {
                "#{path_prefix}schemas/password_reset_initiate_schema.cr",
                ECR.render(
                  "#{__DIR__}/templates/app/schemas/password_reset_initiate_schema.cr.ecr"
                ),
              },
              {
                "#{path_prefix}schemas/password_update_schema.cr",
                ECR.render(
                  "#{__DIR__}/templates/app/schemas/password_update_schema.cr.ecr"
                ),
              },
              {
                "#{path_prefix}schemas/sign_in_schema.cr",
                ECR.render("#{__DIR__}/templates/app/schemas/sign_in_schema.cr.ecr"),
              },
              {
                "#{path_prefix}schemas/sign_up_schema.cr",
                ECR.render("#{__DIR__}/templates/app/schemas/sign_up_schema.cr.ecr"),
              },
              {
                "#{path_prefix}templates/#{context.label}/emails/password_reset.html",
                ECR.render(
                  "#{__DIR__}/templates/app/templates/emails/password_reset.html.ecr"
                ),
              },
              {
                "#{path_prefix}templates/#{context.label}/password_reset_confirm.html",
                ECR.render(
                  "#{__DIR__}/templates/app/templates/password_reset_confirm.html.ecr"
                ),
              },
              {
                "#{path_prefix}templates/#{context.label}/password_reset_initiate.html",
                ECR.render(
                  "#{__DIR__}/templates/app/templates/password_reset_initiate.html.ecr"
                ),
              },
              {
                "#{path_prefix}templates/#{context.label}/password_update.html",
                ECR.render(
                  "#{__DIR__}/templates/app/templates/password_update.html.ecr"
                ),
              },
              {
                "#{path_prefix}templates/#{context.label}/profile.html",
                ECR.render("#{__DIR__}/templates/app/templates/profile.html.ecr"),
              },
              {
                "#{path_prefix}templates/#{context.label}/sign_in.html",
                ECR.render("#{__DIR__}/templates/app/templates/sign_in.html.ecr"),
              },
              {
                "#{path_prefix}templates/#{context.label}/sign_up.html",
                ECR.render("#{__DIR__}/templates/app/templates/sign_up.html.ecr"),
              },
            ]
          end

          def self.spec_files(context : Context)
            spec_helper_inner = ECR.render("#{__DIR__}/templates/spec/spec_helper_inner.cr.ecr")
            spec_helper_outer = ECR.render("#{__DIR__}/templates/spec/spec_helper_outer.cr.ecr")

            [
              {
                "apps/#{context.label}/emails/password_reset_email_spec.cr",
                ECR.render("#{__DIR__}/templates/spec/emails/password_reset_email_spec.cr.ecr"),
              },
              {
                "apps/#{context.label}/emails/spec_helper.cr",
                spec_helper_inner,
              },
              {
                "apps/#{context.label}/handlers/concerns/require_anonymous_user_spec.cr",
                ECR.render(
                  "#{__DIR__}/templates/spec/handlers/concerns/require_anonymous_user_spec.cr.ecr"
                ),
              },
              {
                "apps/#{context.label}/handlers/concerns/require_signed_in_user_spec.cr",
                ECR.render(
                  "#{__DIR__}/templates/spec/handlers/concerns/require_signed_in_user_spec.cr.ecr"
                ),
              },
              {
                "apps/#{context.label}/handlers/concerns/spec_helper.cr",
                spec_helper_inner,
              },
              {
                "apps/#{context.label}/handlers/password_reset_confirm_handler_spec.cr",
                ECR.render(
                  "#{__DIR__}/templates/spec/handlers/password_reset_confirm_handler_spec.cr.ecr"
                ),
              },
              {
                "apps/#{context.label}/handlers/password_reset_initiate_handler_spec.cr",
                ECR.render(
                  "#{__DIR__}/templates/spec/handlers/password_reset_initiate_handler_spec.cr.ecr"
                ),
              },
              {
                "apps/#{context.label}/handlers/password_update_handler_spec.cr",
                ECR.render(
                  "#{__DIR__}/templates/spec/handlers/password_update_handler_spec.cr.ecr"
                ),
              },
              {
                "apps/#{context.label}/handlers/profile_handler_spec.cr",
                ECR.render("#{__DIR__}/templates/spec/handlers/profile_handler_spec.cr.ecr"),
              },
              {
                "apps/#{context.label}/handlers/sign_in_handler_spec.cr",
                ECR.render("#{__DIR__}/templates/spec/handlers/sign_in_handler_spec.cr.ecr"),
              },
              {
                "apps/#{context.label}/handlers/sign_out_handler_spec.cr",
                ECR.render("#{__DIR__}/templates/spec/handlers/sign_out_handler_spec.cr.ecr"),
              },
              {
                "apps/#{context.label}/handlers/sign_up_handler_spec.cr",
                ECR.render("#{__DIR__}/templates/spec/handlers/sign_up_handler_spec.cr.ecr"),
              },
              {
                "apps/#{context.label}/handlers/spec_helper.cr",
                spec_helper_inner,
              },
              {
                "apps/#{context.label}/spec_helper.cr",
                spec_helper_outer,
              },
              {
                "apps/#{context.label}/schemas/password_reset_confirm_schema_spec.cr",
                ECR.render(
                  "#{__DIR__}/templates/spec/schemas/password_reset_confirm_schema_spec.cr.ecr"
                ),
              },
              {
                "apps/#{context.label}/schemas/password_reset_initiate_schema_spec.cr",
                ECR.render(
                  "#{__DIR__}/templates/spec/schemas/password_reset_initiate_schema_spec.cr.ecr"
                ),
              },
              {
                "apps/#{context.label}/schemas/password_update_schema_spec.cr",
                ECR.render(
                  "#{__DIR__}/templates/spec/schemas/password_update_schema_spec.cr.ecr"
                ),
              },
              {
                "apps/#{context.label}/schemas/sign_in_schema_spec.cr",
                ECR.render("#{__DIR__}/templates/spec/schemas/sign_in_schema_spec.cr.ecr"),
              },
              {
                "apps/#{context.label}/schemas/sign_up_schema_spec.cr",
                ECR.render("#{__DIR__}/templates/spec/schemas/sign_up_schema_spec.cr.ecr"),
              },
              {
                "apps/#{context.label}/schemas/spec_helper.cr",
                spec_helper_inner,
              },
            ]
          end
        end
      end
    end
  end
end
