#!/bin/sh -e

batch_number=6
spec_files=$(find ./spec -name "*_spec.cr")
num_files=$(echo "$spec_files" | wc -l)
batch_size=$(( $num_files / $batch_number ))

i=0
while [ $i -lt $batch_number ]; do
  batch_files=$(echo "$spec_files" | tail -n +$(( $batch_size * $i + 1 )) | head -$batch_size)

  echo "Running batch $(($i + 1))..."
  echo "$batch_files" | xargs crystal spec
  i=$((i + 1))
  echo ""
done
